backend:
  name: git-gateway
  branch: master

media_folder: static/assets/uploads
public_folder: /assets/uploads

collections:
  - name: bg_images
    label: "Imagen de fondo"
    folder: content/bg_images
    create: true
    fields:
      - { name: title, label: "Título" }
      - { name: path, label: "Ruta" }
      - { name: date, label: "Fecha", widget: date }
      - { name: body, label: "Contenido", widget: markdown }
  - name: sucursal
    label: "Sucursal"
    folder: content/sucursales
    create: true
    fields:
      - { name: title, label: "Nombre", required: true }
      - { name: address, label: "Dirección", widget: text }
      - { name: phone, label: "Teléfono" }
      - { name: main, label: "Matriz", widget: boolean }
      - name: "coords"
        label: "Coordenadas"
        widget: "object"
        required: true
        fields: 
            - { name: latitude, label: "Latitud", required: true, pattern: "^-?[0-9]*(.?[0-9]+)?$" }
            - { name: longitude, label: "Longitud", required: true, pattern: "^-?[0-9]*(.?[0-9]+)?$" }
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: title, label: "Título" }
      - { name: path, label: "Ruta" }
      - { name: space, label: "Espacio", default: "blog" }
      - { name: date, label: "Fecha", widget: date }
      - { name: body, label: "Contenido", widget: markdown }